[phases.setup]
aptPkgs = ["unzip"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["reflex init"]

[start]
cmd = "reflex run --env prod"
