services:
  - type: web
    name: threads-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /ping
    autoDeploy: true
    preDeployCommand: "echo 'Pre-deploy cleanup'"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: threads-db
          property: connectionString
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: THREADS_APP_ID
        sync: false
      - key: THREADS_APP_SECRET
        sync: false
      - key: REFLEX_ENV
        value: prod
      - key: BASE_URL
        sync: false
      - key: PORT
        value: 8000

databases:
  - name: threads-db
    plan: free
    databaseName: threads
    user: threads
